// lang-en.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'login': 'Login',
  'registration': 'Registration',
  'register': 'Register',
  'otp': 'One Time Password',
  'firstName': 'First Name',
  'lastName': 'Last Name',
  'email': 'Email Address',
  'password': 'Password',
  'oldPassword': 'Old Password',
  'newPassword': 'New Password',
  'confirmPassword': 'Confirm Password',
  'createAccount': 'Create an account',
  'recover': 'Recover Password',
  'signUp': 'Sign up',
  'verifyOTP': 'Verify OTP',
  'userName': 'User Name',
  'fatherName': 'Father Name',
  'aadharNumber': 'Aadhar Number',
  'mobileNumber': 'Mobile Number',
  'dntHaveAccount': 'Don\'t have an account yet?',
  'forgotPwd': 'Forgot your account password?',
  'alreadyAccount': 'Aready have an account?',
  'home': 'Home',
  'term': 'Token Terms',
  'blog': 'Blog',
  'logout': 'Logout',
  'modeofTransferReq': 'Please select mode of transfer',
  'frstNameRqrd': 'Please enter your first name',
  'lastNameRqrd': 'Please enter your last name',
  'userNameRqrd': 'Please enter your user name',
  'validUserName': 'Username atleast 1 Capital, 1 small and 1 digit',
  'userNameLnth': 'User name length in between 8 to 25',
  'fatherNameRqrd': 'Please enter your father name',
  'aadharNumberRqrd': 'Please enter your aadhar number',
  'validAadharNumber': 'Accept only digits',
  'aadharNumberLenth': 'Please enter 12 digit aadhar number',
  'frstNameLnth': 'Length must be in between 3 to 50',
  'fatherNameLnth': 'Length must be in between 3 to 50',
  'lastNameLnth': 'Length must be in between 2 to 50',
  'emailRqrd': 'Email address is required',
  'validEmail': 'Enter valid email address',
  'validPwd': 'At least contain 1 non-letter and 1 capital letter',
  'pwdLenth': 'Password length must be between 8 to 50 chars',
  'pwdRqrd': 'A Password is required',
  'cnfrmPwdRqrd': 'A Confirm password is required',
  'cnfrmPwdNtMatched': 'Passwords do not match',
  'sponserID': 'Sponser ID',
  'sponserName': 'Sponser Name',
  'sponserIDRqrd': 'Please enter sponser Id',
  'sponserNameRqrd': 'Please enter sponser name',
  'underID': 'Under ID',
  'underName': 'Under Name',
  'underIDRqrd': 'Please enter under Id',
  'underNameRqrd': 'Please enter under name',
  'schoolCode': 'School Code',
  'searchByName': 'Search by Name',
  'searchByLoanID': 'Search by Loan ID',
  'noLoandetails': 'There are no loans to show',
  'noLoanDocumentdetails': 'There are no loans documents for this loan',

  // Secret Key variables
  'generateSecretKey': 'Generate Secret Key',
  'phoneNumber': 'Phone Number',
  'phoneNumberRqrd': 'Please enter phone number.',
  'validPhoneNumber': 'Please enter valid phone number',
  'validLength': 'Please enter 10 digit phone number',
  'secretkey': 'Generate Key',
  'secretCode': 'Secret Key',
  'secretCodeRqrd': 'Please enter secret key',
  'secretKeyLength': 'Please provide valid secret key',
  'verifySecretKey': 'Verify Secret Key',
  'registerSuccessStatus': 'User Registered successfully!',
  'registerFailedStatus': 'Oops! There has benn an error from server side, your registeration failed.Please try again.',

  //Earn Loans
  'earnLoansTitle': 'Earn Loans',
  //Address validation messages
  'address1Rqrd': 'Please provide address field',
  'address1Lnth': 'Address length should be in between 3 to 250 chars',
  'address2Rqrd': 'Please provide address2 field',
  'address2Lnth': 'Address2 length should be in between 4 to 250 chars',
  'cityRqrd': 'Please provide city name field',
  'cityLnth': 'City name length should be in between 2 to 50 chars',
  'validCity': 'Please provide valid city name',
  'stateRqrd': 'Please provide state name field',
  'validStateLength': 'State name length should be in between 2 to 50 chars',
  'validState': 'Please provide valid state name',
  'zipcodeRqrd': 'Please provide Zipcode field',
  'zipcodeLenth': 'Zipcode length should be 6 digits only',
  'validZipcode': 'Please provide Zipcode field',
  'countryRqrd': 'Please provide country field',
  'validcountry': 'Please provide valid conuntry name',
  'countryLenth': 'Country name  should be in between 2 to 5o chars',

  'bankIDRqrd': 'Please select bank name',
  'nomineeNameRqrd': 'Please provide nominee name',
  'nomineeNameLnth': 'Nominee name length should be in between 3 to 50 chars',
  'nomineeAddressRqrd': 'Please provide nominee address',
  'nomineeAddressLnth': 'Nominee address length should be in between 2 to 250 chars',
  'PhoneNumberLength': 'Phone number should be 10 digits',
  'validNomineePhoneNumber': 'Please provide valid phone number',
  'accountHolderNameRqrd': 'Please provide account holder name',
  'accountHolderNameLnth': 'Account holder name length should be in between 3 to 50 chars',
  'accountNumberRqrd': 'Please provide account number',
  'accountNumberLnth': 'Account number length should be in between 4 to 50 chars',
  'confirmAccountNumberRqrd': 'Re-enter account number',
  'confirmAccountNumberNtMatched': 'Acount number not matched',
  'iFSCCodeRqrd': 'Please provide IFSC code',
  'iFSCCodeLenth': 'Please provide valid IFSC code',
  'BranchNameLenth': 'Branch name length should be in between 2 to 50 chars',
  'branchAddressLenth': 'Branch address length should be in between 2 to 50 chars',

  'roles': 'Roles',
  'role': 'Role',
  'isactive': 'Is Active',
  'rolesave': 'Save',
  'rolerequired': 'Role is required',
  'reset': 'Reset',
  'updaterole': 'Update',

  //  Master screen variables
  'masterScreen': 'Master Screen',
  'documentationFee': 'Documentation & Admin Fee',
  'prePaidLoan': 'Prepaid Loan Charges',
  'franchisecommission': 'Franchise & Commission',
  'area': 'Area',
  'district': 'District',
  'districtCluster': 'District Cluster',
  'state': 'State',
  'stateCluster': 'State Cluster',
  'mother': 'Mother',
  'documentationFeeRqrd': 'Please provide Documentation & Admin Fee',
  'validdocumentationFee': 'Please provide valid Documentation & Admin Fee',
  'prePaidLoanRqrd': 'Please provide Prepaid Loan Charges',
  'validPrePaidLoan': 'Please provide valid Prepaid Loan Charges',
  'areaRqrd': 'Please provide area charges',
  'validArea': 'Please provide valid area charges',
  'districtChargesRqrd': 'Please provide District charges',
  'validDistrictCharges': 'Please provide valid District charges',
  'districtClusterChangesRqrd': 'Please provide District cluster charges',
  'validDistrictClusterChangesse': 'Please provide valid District cluster charges',
  'stateChargesRqrd': 'Please provide State charges',
  'validStateCharges': 'Please provide valid State charges',
  'stateClusterChangesRqrd': 'Please provide State cluster charges',
  'validStateClusterCharges': 'Please provide valid State cluster charges',
  'motherChargesRqrd': 'Please provide Mother charges',
  'validMotherCharges': 'Please provide valid Mother charges',
  'SGSTRqrd': 'SGST charges required',
  'validSGSTCharges': 'Please provide valid SGST charges',
  'CGSTRqrd': 'CGST charges required',
  'validCGST': 'Please provide valid CGST charges',
  'IGSTRqrd': 'IGST charges required',
  'validIGST': 'Please provide valid IGST charges',
  'TDSRqrd': 'TDS charges required',
  'validTDS': 'Please provide valid TDS charges',

  'viewLoanDetails': 'Loan Details',
  'editLoanDetails': 'Edit Loan Details',
  'loanAmountRqrd': 'Loan amount required',
  'validLoanAmount': 'Enter valid loan amount',
  'noRecords': 'No records found',
  'dataLoading': 'Loading....',
  // common varaibles
  'doYouQuestion': 'Any Questions? Contact us at',
  'submit': 'Submit',
  'save': 'Save',
  'userInfo': 'User Information',
  'changePassword': 'Change Password',
  'chngePhnNumber': 'Change Phone Number',
  'phnNumber': 'Phone Number',
  'settings': 'User Settings'
};

